# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
import numpy as np

arr = np.arange(0, 10)
arr = arr.reshape((2, 5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [25]:
# arr1 = np.arange(0, 5)
# arr2 = np.arange(5, 10)
# arr3 = np.ones((5), dtype=np.int32)
# arr4 = np.ones((5), dtype=np.int32)

# arr5 = np.stack((arr1, arr2, arr3, arr4))
# arr5

arr1 = np.arange(0, 10).reshape(2, 5)
arr2 = np.ones((2, 5), dtype=np.int32)

arr3 = np.stack((arr1, arr2)).reshape(4, 5)
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [26]:
arr1 = np.arange(0, 10).reshape(2, 5)
arr2 = np.ones((2, 5), dtype=np.int32)

arr3 = np.hstack((arr1, arr2))
arr3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [28]:
# TO CONVERT AN NESTED ARRAY TO 1D, WE USE ravel() numpy method.
arr = np.arange(0, 10).reshape(5, 2)
flat_arr = arr.ravel()
flat_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [31]:
arr = np.arange(0, 15).reshape((3, 5))
arr.reshape((15))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [35]:
arr = np.arange(0, 15)
arr2 = arr.reshape((5, 3))
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [41]:
arr = np.arange(0, 25).reshape(5, 5)
arr_square = arr ** 2
print(arr_square)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [53]:
arr = np.random.randint(1, 100, (5, 6))
mean = arr.mean()
print(mean)

47.666666666666664


## Question:9

### Find the standard deviation of the previous array in Q8?

In [55]:
arr.std()

31.79972047396364

## Question:10

### Find the median of the previous array in Q8?

In [56]:
np.median(arr)

51.0

## Question:11

### Find the transpose of the previous array in Q8?

In [58]:
transpose = arr.T
transpose

array([[16, 14,  5, 10, 72],
       [67, 90, 62, 37, 31],
       [54, 78,  4,  9, 98],
       [ 3, 19, 48, 57, 98],
       [19, 88, 75, 25,  4],
       [83, 82, 80, 42, 60]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [66]:
arr = np.arange(1, 17).reshape((4, 4))
np.sum(np.diagonal(arr))


34

## Question:13

### Find the determinant of the previous array in Q12?

In [67]:
np.linalg.det(arr)

-1.820448242817726e-31

## Question:14

### Find the 5th and 95th percentile of an array?

In [73]:
percentile_5 = np.percentile(arr, 5)
percentile_95 = np.percentile(arr, 95)

print(percentile_5)
print(percentile_95)

1.75
15.25


## Question:15

### How to find if a given array has any null values?

##### We can find this by using np.isnan(arr).any(), example:

In [89]:
arr = np.array([[1, 2, 3, 4, 5],
               [6, np.NaN, np.NaN, 9, np.NaN],
               [7, 8, 11, 12, np.NaN]])

np.isnan(arr).any()

True