# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [31]:
null_vector = np.zeros((10))
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [5]:
arr_10_to_49 = np.arange(10, 49) # 49 is exclusive

4. Find the shape of previous array in question 3

In [7]:
shape_arr_10_to_49 = arr_10_to_49.shape

5. Print the type of the previous array in question 3

In [8]:
print(arr_10_to_49.dtype)

int32


6. Print the numpy version and the configuration


In [11]:
print(np.version)

<module 'numpy.version' from 'C:\\Users\\BB\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>


7. Print the dimension of the array in question 3


In [14]:
print(len(arr_10_to_49.shape))

1


8. Create a boolean array with all the True values

In [17]:
boolean_array = np.array([True for i in range(10)])
# print(boolean_array)

9. Create a two dimensional array




In [18]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

10. Create a three dimensional array



In [20]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6,], [7, 8, 9]], [[1, 2, 3], [4, 5, 6,], [7, 8, 9]]])
# arr_3d.shape

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [30]:
arr = np.arange(1, 10)
reversed_arr = np.array(sorted(arr, reverse=True))
print(reversed_arr)

[9 8 7 6 5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [32]:
null_vector_1 = np.zeros((10))
null_vector_1[4] = 1
null_vector_1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [34]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [37]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype('float32')
arr.dtype

dtype('float32')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [39]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])

arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [40]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])

arr3 = (arr1 == arr2)
print(arr3)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [42]:
arr = np.arange(0, 10)
arr = arr[arr%2 == 1]
arr

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [43]:
arr = np.arange(0, 10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [44]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [53]:
arr = np.ones((9, 9))
arr[1:arr.shape[0]-1, 1:arr.shape[1]-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [54]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[arr2d==5] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [58]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0, 0] = 64
arr3d[0, 0]

array([64, 64, 64])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [60]:
arr_2d = np.arange(0, 9).reshape((3, 3))
first_row = arr2d[0]
first_row

array([1, 2, 3])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [61]:
arr_2d = np.arange(0, 9).reshape((3, 3))
second_element = arr_2d[1, 1]
second_element

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [63]:
arr_2d = np.arange(0, 9).reshape((3, 3))
third_column = arr_2d[:2, 2]
third_column

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [69]:
arr_10_10 = np.random.random((10, 10))
minimum = np.min(arr_10_10)
maximum = np.max(arr_10_10)
print(minimum)
print(maximum)

0.01285248029124797
0.9883100250901333


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [70]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
intersection = np.intersect1d(a, b)
intersection

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [72]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a == b)
c

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [76]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names != 'Will']

array([[-0.02722678, -0.42745757,  0.10607796,  1.14378389],
       [-1.35804615,  1.02202174, -0.28415443,  0.21903575],
       [ 0.99694235, -1.07883077, -0.3760895 , -1.19413274],
       [ 0.90409252, -1.41514107, -0.11230824,  0.11775679],
       [ 0.70928151,  0.83196135,  0.40221035,  1.03498078]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [89]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
condition = np.logical_and(names!='Will', names!='Joe')
data[condition]

array([[ 1.8830384 , -1.60169537, -0.64381772,  0.52430932],
       [ 2.46733673,  0.19845397,  1.46020326,  0.39306543]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [91]:
arr = np.linspace(1, 15, 15).reshape((5, 3))
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [92]:
arr = np.linspace(1, 16, 16).reshape((2, 2, 4))
arr

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [93]:
transpose = arr.T
transpose

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [101]:
arr = np.abs(np.random.randn(10))
sqrt_arr = np.sqrt(arr)
sqrt_arr[sqrt_arr<0.5] = 0
sqrt_arr

array([0.75799905, 1.48846079, 0.79649196, 1.46131031, 0.        ,
       0.70416704, 1.05332604, 0.        , 0.60632401, 0.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [105]:
a = np.random.randn(12)
b = np.random.randn(12)
max_elements = np.array([np.max(a), np.max(b)])
max_elements

array([1.16803799, 1.35763981])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [107]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names = np.unique(names)
unique_names = np.sort(unique_names)
unique_names

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [120]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
intersect = np.intersect1d(a, b)
for element in intersect:
    a = np.where(a!=element)
a

(array([0, 1, 2, 3], dtype=int64),)

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [124]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:, 2] = newColumn
sampleArray

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [125]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

product = np.dot(x, y)
product

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [130]:
matrix = np.random.randn(20)
print(matrix)
s = np.cumsum(matrix)
print(s)

[-0.88879922 -1.79638419 -0.29914538  0.66453172  0.11072668  1.74517532
  0.47880689 -1.33414166 -1.25960813  1.97582692  0.31309938 -1.57207726
  1.20870363 -0.46304243  1.57332859  0.39774179  0.24790654 -0.7857743
 -0.62262713  0.65261011]
[-0.88879922 -2.68518341 -2.98432879 -2.31979706 -2.20907038 -0.46389506
  0.01491184 -1.31922983 -2.57883795 -0.60301104 -0.28991165 -1.86198891
 -0.65328528 -1.11632771  0.45700088  0.85474266  1.10264921  0.31687491
 -0.30575223  0.34685788]
